/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getLiveHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getReadyHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getCurrentSession"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/documents/uploads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createDocumentUpload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/documents/{id}/actions/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["completeDocumentUpload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/documents/{id}/actions/download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createDocumentDownload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/documents/{id}/public-links": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createDocumentPublicLink"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/documents/{id}/public-links/{linkId}/actions/revoke": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["revokeDocumentPublicLink"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/public/document-links/{token}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["resolvePublicDocumentLink"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/intake/actions/check-duplicates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["checkIntakeDuplicates"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/intake/leads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createIntakeLead"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/customers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listCustomers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/customers/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getCustomer"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/leads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listLeads"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/leads/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getLead"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/leads/{id}/notes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["addLeadNote"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/leads/{id}/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["addLeadTask"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/leads/{id}/tasks/{taskId}/actions/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["completeLeadTask"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/leads/{id}/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["linkLeadDocument"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/leads/{id}/actions/{action}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["transitionLead"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/pricing/configurations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listPricingConfigurations"];
    put?: never;
    post: operations["createPricingConfiguration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/pricing/versions/{id}/actions/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["activatePricingVersion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/estimates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listEstimates"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/estimate-versions/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getEstimateVersion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/leads/{id}/estimate-versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createEstimateVersionForLead"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/estimates/{id}/actions/revise": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["reviseEstimate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/estimate-versions/{id}/actions/submit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["submitEstimateVersion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/estimate-versions/{id}/actions/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["approveEstimateVersion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/estimate-versions/{id}/actions/create-quote": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createQuoteFromEstimateVersion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/quotes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listQuotes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/quotes/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getQuote"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/quotes/{id}/actions/revise": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["reviseQuote"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/quote-versions/{id}/actions/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["approveQuoteVersion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/quote-versions/{id}/actions/send": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sendQuoteVersion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/quote-versions/{id}/actions/withdraw": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["withdrawQuoteVersion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/quote-versions/{id}/actions/expire": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["expireQuoteVersion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/public/quotes/{token}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPublicQuote"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/public/quotes/{token}/actions/accept": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["acceptPublicQuote"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/public/quotes/{token}/actions/decline": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["declinePublicQuote"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    LiveHealthDto: {
      /** @example ok */
      status: string;
      /** Format: date-time */
      timestamp: string;
    };
    ReadinessChecksDto: {
      /** @enum {string} */
      database: "ready";
      /** @enum {string} */
      migrations: "ready";
      /** @enum {string} */
      objectStorage: "ready";
      /** @enum {string} */
      worker: "ready" | "skipped";
    };
    ReadyHealthDto: {
      checks: components["schemas"]["ReadinessChecksDto"];
      /** @example ready */
      status: string;
      /** Format: date-time */
      timestamp: string;
    };
    ApiErrorDetailDto: {
      code: string;
      correlationId: string;
      details?: Record<string, never>;
      message: string;
    };
    ApiErrorResponseDto: {
      error: components["schemas"]["ApiErrorDetailDto"];
    };
    SessionDto: {
      permissions: string[];
      /** Format: uuid */
      tenantId: string;
      /** Format: uuid */
      userId: string;
    };
    CreateDocumentUploadDto: {
      /** @example supplier-ticket.pdf */
      originalFilename: string;
      /** @enum {string} */
      mediaType: "application/pdf" | "image/jpeg" | "image/png" | "text/plain";
      sizeBytes: number;
      /** @example aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa */
      sha256: string;
    };
    DocumentDto: {
      /** Format: uuid */
      id: string;
      mediaType: string;
      originalFilename: string;
      sizeBytes: number;
      /** @enum {string} */
      status: "pending" | "available" | "rejected";
    };
    DocumentUploadTargetDto: {
      /** Format: date-time */
      expiresAt: string;
      headers: {
        [key: string]: string;
      };
      /** Format: uri */
      url: string;
    };
    CreateDocumentUploadResponseDto: {
      document: components["schemas"]["DocumentDto"];
      upload: components["schemas"]["DocumentUploadTargetDto"];
    };
    DocumentDownloadDto: {
      /** Format: date-time */
      expiresAt: string;
      /** Format: uri */
      url: string;
    };
    CreateDocumentPublicLinkDto: {
      /** @default 86400 */
      expiresInSeconds: number;
      /**
       * @default download
       * @enum {string}
       */
      scope: "download";
    };
    DocumentPublicLinkDto: {
      /** Format: date-time */
      expiresAt: string;
      /** Format: uuid */
      linkId: string;
      /** @enum {string} */
      scope: "download";
      /** @description Plaintext capability returned only to the creator */
      token: string;
    };
    PublicDocumentDownloadDto: {
      /** Format: date-time */
      expiresAt: string;
      /** Format: uri */
      url: string;
      document: components["schemas"]["DocumentDto"];
    };
    NewServiceLocationDto: {
      label: string;
      addressLine1: string;
      addressLine2?: string;
      city: string;
      region: string;
      postalCode: string;
      accessNotes?: string;
    };
    DuplicateCheckDto: {
      customerName?: string;
      email?: string;
      phone?: string;
      serviceLocation?: components["schemas"]["NewServiceLocationDto"];
    };
    DuplicateWarningDto: {
      /** @enum {string} */
      code: "customer_name" | "contact_email" | "contact_phone" | "service_address";
      /** @enum {string} */
      entityType: "CustomerAccount" | "Contact" | "ServiceLocation";
      /** Format: uuid */
      entityId: string;
      display: string;
    };
    DuplicateCheckResponseDto: {
      warnings: components["schemas"]["DuplicateWarningDto"][];
    };
    NewCustomerAccountDto: {
      displayName: string;
      /** @enum {string} */
      customerType: "individual" | "business";
      /** @enum {string} */
      preferredContactMethod?: "phone" | "email" | "text";
      billingContactSummary?: string;
    };
    NewContactDto: {
      firstName: string;
      lastName: string;
      email?: string;
      phone?: string;
      /** @enum {string} */
      preferredContactMethod: "phone" | "email" | "text";
    };
    MaterialDeliveryLeadInputDto: {
      materialDescription: string;
      /** @description Positive decimal with no more than three fractional digits */
      estimatedQuantity: string;
      /** @enum {string} */
      quantityUnit: "tons" | "cubic_yards" | "loads";
      deliveryInstructions?: string;
    };
    DumpTrailerRentalLeadInputDto: {
      /** Format: date */
      rentalStartDate: string;
      /** Format: date */
      rentalEndDate: string;
      debrisType: string;
      deliveryInstructions?: string;
    };
    CreateIntakeLeadDto: {
      /** Format: uuid */
      customerAccountId?: string;
      customer?: components["schemas"]["NewCustomerAccountDto"];
      /** Format: uuid */
      primaryContactId?: string;
      primaryContact?: components["schemas"]["NewContactDto"];
      /** Format: uuid */
      serviceLocationId?: string;
      serviceLocation?: components["schemas"]["NewServiceLocationDto"];
      /** @enum {string} */
      serviceType: "material_delivery" | "dump_trailer_rental";
      /** @enum {string} */
      source: "phone" | "website" | "email" | "referral" | "repeat" | "other";
      summary: string;
      materialDelivery?: components["schemas"]["MaterialDeliveryLeadInputDto"];
      dumpTrailerRental?: components["schemas"]["DumpTrailerRentalLeadInputDto"];
    };
    CustomerAccountDto: {
      /** Format: uuid */
      id: string;
      displayName: string;
      /** @enum {string} */
      customerType: "individual" | "business";
      /** @enum {string} */
      status: "active" | "inactive";
      /** @enum {string|null} */
      preferredContactMethod?: "phone" | "email" | "text" | null;
      createdAt: string;
    };
    ContactDto: {
      /** Format: uuid */
      id: string;
      displayName: string;
      email?: string | null;
      phone?: string | null;
      /** @enum {string} */
      preferredContactMethod: "phone" | "email" | "text";
    };
    ServiceLocationDto: {
      /** Format: uuid */
      id: string;
      label: string;
      addressLine1: string;
      addressLine2?: string | null;
      city: string;
      region: string;
      postalCode: string;
      accessNotes?: string | null;
    };
    LeadDto: {
      /** Format: uuid */
      id: string;
      leadNumber: string;
      /** @enum {string} */
      serviceType: "material_delivery" | "dump_trailer_rental";
      /** @enum {string} */
      status:
        | "new"
        | "contacting"
        | "qualified"
        | "estimating"
        | "quoted"
        | "accepted"
        | "lost"
        | "cancelled"
        | "duplicate"
        | "disqualified";
      /** @enum {string} */
      source: "phone" | "website" | "email" | "referral" | "repeat" | "other";
      summary: string;
      customer: components["schemas"]["CustomerAccountDto"];
      primaryContact: components["schemas"]["ContactDto"];
      serviceLocation: components["schemas"]["ServiceLocationDto"];
      materialDelivery?: components["schemas"]["MaterialDeliveryLeadInputDto"] | null;
      dumpTrailerRental?: components["schemas"]["DumpTrailerRentalLeadInputDto"] | null;
      terminalReason?: string | null;
      createdAt: string;
      updatedAt: string;
    };
    CreateIntakeLeadResponseDto: {
      lead: components["schemas"]["LeadDto"];
      duplicateWarnings: components["schemas"]["DuplicateWarningDto"][];
    };
    CustomerListResponseDto: {
      items: components["schemas"]["CustomerAccountDto"][];
      total: number;
    };
    CustomerDetailDto: {
      /** Format: uuid */
      id: string;
      displayName: string;
      /** @enum {string} */
      customerType: "individual" | "business";
      /** @enum {string} */
      status: "active" | "inactive";
      /** @enum {string|null} */
      preferredContactMethod?: "phone" | "email" | "text" | null;
      createdAt: string;
      contacts: components["schemas"]["ContactDto"][];
      serviceLocations: components["schemas"]["ServiceLocationDto"][];
      leads: components["schemas"]["LeadDto"][];
    };
    LeadListResponseDto: {
      items: components["schemas"]["LeadDto"][];
      total: number;
    };
    LeadNoteDto: {
      /** Format: uuid */
      id: string;
      body: string;
      /** @enum {string} */
      visibility: "internal" | "customer";
      createdAt: string;
    };
    LeadTaskDto: {
      /** Format: uuid */
      id: string;
      title: string;
      /** @enum {string} */
      status: "open" | "completed" | "cancelled";
      dueAt?: string | null;
      completedAt?: string | null;
    };
    LeadDocumentDto: {
      /** Format: uuid */
      id: string;
      originalFilename: string;
      mediaType: string;
      purpose: string;
    };
    LeadTimelineItemDto: {
      /** Format: uuid */
      id: string;
      eventType: string;
      occurredAt: string;
      metadata: {
        [key: string]: unknown;
      };
    };
    LeadDetailDto: {
      /** Format: uuid */
      id: string;
      leadNumber: string;
      /** @enum {string} */
      serviceType: "material_delivery" | "dump_trailer_rental";
      /** @enum {string} */
      status:
        | "new"
        | "contacting"
        | "qualified"
        | "estimating"
        | "quoted"
        | "accepted"
        | "lost"
        | "cancelled"
        | "duplicate"
        | "disqualified";
      /** @enum {string} */
      source: "phone" | "website" | "email" | "referral" | "repeat" | "other";
      summary: string;
      customer: components["schemas"]["CustomerAccountDto"];
      primaryContact: components["schemas"]["ContactDto"];
      serviceLocation: components["schemas"]["ServiceLocationDto"];
      materialDelivery?: components["schemas"]["MaterialDeliveryLeadInputDto"] | null;
      dumpTrailerRental?: components["schemas"]["DumpTrailerRentalLeadInputDto"] | null;
      terminalReason?: string | null;
      createdAt: string;
      updatedAt: string;
      notes: components["schemas"]["LeadNoteDto"][];
      tasks: components["schemas"]["LeadTaskDto"][];
      documents: components["schemas"]["LeadDocumentDto"][];
      timeline: components["schemas"]["LeadTimelineItemDto"][];
    };
    CreateLeadNoteDto: {
      body: string;
      /**
       * @default internal
       * @enum {string}
       */
      visibility: "internal" | "customer";
    };
    CreateLeadTaskDto: {
      title: string;
      /** Format: date-time */
      dueAt?: string;
      /** Format: uuid */
      assignedUserId?: string;
    };
    LinkLeadDocumentDto: {
      /** Format: uuid */
      documentId: string;
      purpose: string;
    };
    TransitionLeadDto: {
      reason?: string;
    };
    PricingRuleDto: {
      /** Format: uuid */
      id: string;
      code: string;
      label: string;
      calculationType: string;
      sequence: number;
      parameters: {
        [key: string]: unknown;
      };
    };
    PricingVersionDto: {
      /** Format: uuid */
      id: string;
      versionNumber: number;
      /** @enum {string} */
      status: "draft" | "active" | "retired";
      /** Format: date-time */
      effectiveAt?: string | null;
      rules: components["schemas"]["PricingRuleDto"][];
    };
    PricingPolicyDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** @enum {string} */
      serviceType: "material_delivery" | "dump_trailer_rental";
      /** @enum {string} */
      status: "draft" | "active" | "retired";
      versions: components["schemas"]["PricingVersionDto"][];
    };
    SupplierCostDto: {
      /** Format: uuid */
      id: string;
      materialName: string;
      supplierName: string;
      supplierLocationName: string;
      /** @enum {string} */
      unit: "tons" | "cubic_yards" | "loads";
      unitCostCents: number;
      /** @enum {string} */
      status: "active" | "superseded";
    };
    DeliveryZoneDto: {
      /** Format: uuid */
      id: string;
      code: string;
      name: string;
      baseFeeCents: number;
    };
    PricingConfigurationListDto: {
      policies: components["schemas"]["PricingPolicyDto"][];
      supplierCosts: components["schemas"]["SupplierCostDto"][];
      deliveryZones: components["schemas"]["DeliveryZoneDto"][];
    };
    MaterialPricingReferenceInputDto: {
      materialName: string;
      /** @enum {string} */
      unit: "tons" | "cubic_yards" | "loads";
      supplierName: string;
      supplierLocationName: string;
      supplierAddressSummary?: string;
      unitCostCents: number;
    };
    DeliveryZoneInputDto: {
      code: string;
      name: string;
      baseFeeCents: number;
    };
    MaterialPricingConfigurationInputDto: {
      materials: components["schemas"]["MaterialPricingReferenceInputDto"][];
      deliveryZone: components["schemas"]["DeliveryZoneInputDto"];
      markupBasisPoints: number;
      additionalSupplierStopCents: number;
      separatePlacementCents: number;
      depositMinimumCents: number;
      depositRoundUpToCents: number;
    };
    RentalPricingConfigurationInputDto: {
      packageAmountCents: number;
      includedDays: number;
      additionalDayCents: number;
      includedWeightPounds: number;
      overageRateCentsPerPound: number;
      securityDepositCents: number;
    };
    CreatePricingConfigurationDto: {
      policyName: string;
      /** @enum {string} */
      serviceType: "material_delivery" | "dump_trailer_rental";
      materialDelivery?: components["schemas"]["MaterialPricingConfigurationInputDto"];
      dumpTrailerRental?: components["schemas"]["RentalPricingConfigurationInputDto"];
    };
    CreatePricingConfigurationResponseDto: {
      policy: components["schemas"]["PricingPolicyDto"];
      supplierCosts: components["schemas"]["SupplierCostDto"][];
      deliveryZone?: components["schemas"]["DeliveryZoneDto"] | null;
    };
    EstimateListItemDto: {
      /** Format: uuid */
      estimateId: string;
      /** Format: uuid */
      estimateVersionId: string;
      estimateNumber: string;
      /** Format: uuid */
      leadId: string;
      leadNumber: string;
      customerName: string;
      /** @enum {string} */
      serviceType: "material_delivery" | "dump_trailer_rental";
      status: string;
      versionNumber: number;
      recommendedPriceCents: number;
      updatedAt: string;
    };
    EstimateListResponseDto: {
      items: components["schemas"]["EstimateListItemDto"][];
    };
    EstimateCostItemDto: {
      /** Format: uuid */
      id: string;
      description: string;
      quantity: string;
      unit: string;
      unitCostCents: number;
      totalCostCents: number;
    };
    PricingCalculationResultDto: {
      /** Format: uuid */
      id: string;
      code: string;
      label: string;
      calculationType: string;
      amountCents: number;
      details: {
        [key: string]: unknown;
      };
    };
    EstimateVersionDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      estimateId: string;
      estimateNumber: string;
      /** Format: uuid */
      leadId: string;
      leadNumber: string;
      customerName: string;
      /** @enum {string} */
      serviceType: "material_delivery" | "dump_trailer_rental";
      versionNumber: number;
      /** @enum {string} */
      status: "draft" | "pending_approval" | "approved" | "quote_generated" | "superseded";
      pricingPolicyName: string;
      /** Format: uuid */
      pricingVersionId: string;
      pricingVersionNumber: number;
      readiness: string;
      operationalAssessment?: string | null;
      riskAssessment?: string | null;
      purchaseCostCents: number;
      recommendedPriceCents: number;
      approvedQuotePriceCents?: number | null;
      depositCents: number;
      marginCents: number;
      contentHash: string;
      inputSnapshot: {
        [key: string]: unknown;
      };
      costItems: components["schemas"]["EstimateCostItemDto"][];
      calculations: components["schemas"]["PricingCalculationResultDto"][];
      createdAt: string;
    };
    MaterialEstimateItemInputDto: {
      /** Format: uuid */
      supplierCostVersionId: string;
      /** @description Positive decimal with at most three fractional digits */
      quantity: string;
    };
    MaterialEstimateInputDto: {
      items: components["schemas"]["MaterialEstimateItemInputDto"][];
      /** Format: uuid */
      deliveryZoneId: string;
      additionalSupplierStops: number;
      separatePlacements: number;
    };
    CreateEstimateVersionDto: {
      /** Format: uuid */
      pricingVersionId: string;
      materialDelivery?: components["schemas"]["MaterialEstimateInputDto"];
      operationalAssessment?: string;
      riskAssessment?: string;
    };
    QuoteLineItemDto: {
      /** Format: uuid */
      id: string;
      description: string;
      quantity: string;
      unit: string;
      unitPriceCents: number;
      totalCents: number;
    };
    QuoteTermDto: {
      /** Format: uuid */
      id: string;
      title: string;
      body: string;
    };
    QuoteDeliveryDto: {
      /** Format: uuid */
      id: string;
      channel: string;
      recipient: string;
      sentAt: string;
    };
    QuoteVersionDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      quoteId: string;
      quoteNumber: string;
      versionNumber: number;
      /** @enum {string} */
      status:
        | "draft"
        | "ready_to_send"
        | "sent"
        | "viewed"
        | "accepted"
        | "declined"
        | "expired"
        | "withdrawn"
        | "superseded";
      serviceType: string;
      customerName: string;
      customerEmail: string;
      locationLabel: string;
      scope: string;
      subtotalCents: number;
      adjustmentCents: number;
      taxCents: number;
      totalCents: number;
      requiredDepositCents: number;
      contentHash: string;
      /** Format: date-time */
      issuedAt?: string | null;
      /** Format: date-time */
      expiresAt?: string | null;
      /** Format: date-time */
      viewedAt?: string | null;
      lineItems: components["schemas"]["QuoteLineItemDto"][];
      terms: components["schemas"]["QuoteTermDto"][];
      deliveries: components["schemas"]["QuoteDeliveryDto"][];
    };
    QuoteListItemDto: {
      /** Format: uuid */
      quoteId: string;
      /** Format: uuid */
      quoteVersionId: string;
      quoteNumber: string;
      customerName: string;
      serviceType: string;
      status: string;
      versionNumber: number;
      totalCents: number;
      /** Format: date-time */
      expiresAt?: string | null;
      updatedAt: string;
    };
    QuoteListResponseDto: {
      items: components["schemas"]["QuoteListItemDto"][];
    };
    SendQuoteDto: {
      /** @enum {string} */
      channel: "email" | "text" | "link";
      recipient: string;
      /** @default 10 */
      expiresInDays: number;
    };
    SendQuoteResponseDto: {
      quote: components["schemas"]["QuoteVersionDto"];
      /** @description Plaintext capability returned only by the send command */
      token: string;
      customerPath: string;
    };
    PublicQuoteDto: {
      quoteNumber: string;
      versionNumber: number;
      status: string;
      customerName: string;
      serviceType: string;
      locationSummary: string;
      scope: string;
      subtotalCents: number;
      adjustmentCents: number;
      taxCents: number;
      totalCents: number;
      requiredDepositCents: number;
      contentHash: string;
      /** Format: date-time */
      expiresAt: string;
      lineItems: components["schemas"]["QuoteLineItemDto"][];
      terms: components["schemas"]["QuoteTermDto"][];
    };
    AcceptQuoteDto: {
      acceptedName: string;
      contentHash: string;
      consentText: string;
    };
    ProjectDto: {
      /** Format: uuid */
      id: string;
      projectNumber: string;
      status: string;
      serviceType: string;
      outcomeStatement: string;
    };
    AcceptQuoteResponseDto: {
      /** Format: uuid */
      acceptanceId: string;
      /** Format: date-time */
      acceptedAt: string;
      project: components["schemas"]["ProjectDto"];
    };
    DeclineQuoteDto: {
      reason: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getLiveHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LiveHealthDto"];
        };
      };
    };
  };
  getReadyHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyHealthDto"];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  getCurrentSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionDto"];
        };
      };
    };
  };
  createDocumentUpload: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDocumentUploadDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateDocumentUploadResponseDto"];
        };
      };
    };
  };
  completeDocumentUpload: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentDto"];
        };
      };
    };
  };
  createDocumentDownload: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentDownloadDto"];
        };
      };
    };
  };
  createDocumentPublicLink: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDocumentPublicLinkDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentPublicLinkDto"];
        };
      };
    };
  };
  revokeDocumentPublicLink: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        linkId: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  resolvePublicDocumentLink: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicDocumentDownloadDto"];
        };
      };
    };
  };
  checkIntakeDuplicates: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DuplicateCheckDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DuplicateCheckResponseDto"];
        };
      };
    };
  };
  createIntakeLead: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateIntakeLeadDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateIntakeLeadResponseDto"];
        };
      };
    };
  };
  listCustomers: {
    parameters: {
      query?: {
        limit?: number;
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerListResponseDto"];
        };
      };
    };
  };
  getCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerDetailDto"];
        };
      };
    };
  };
  listLeads: {
    parameters: {
      query?: {
        limit?: number;
        status?: string;
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeadListResponseDto"];
        };
      };
    };
  };
  getLead: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeadDetailDto"];
        };
      };
    };
  };
  addLeadNote: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateLeadNoteDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeadNoteDto"];
        };
      };
    };
  };
  addLeadTask: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateLeadTaskDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeadTaskDto"];
        };
      };
    };
  };
  completeLeadTask: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        taskId: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeadTaskDto"];
        };
      };
    };
  };
  linkLeadDocument: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LinkLeadDocumentDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeadDocumentDto"];
        };
      };
    };
  };
  transitionLead: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
        action:
          | "start-contacting"
          | "qualify"
          | "start-estimating"
          | "mark-lost"
          | "cancel"
          | "mark-duplicate"
          | "disqualify";
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransitionLeadDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeadDetailDto"];
        };
      };
    };
  };
  listPricingConfigurations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PricingConfigurationListDto"];
        };
      };
    };
  };
  createPricingConfiguration: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePricingConfigurationDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatePricingConfigurationResponseDto"];
        };
      };
    };
  };
  activatePricingVersion: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PricingVersionDto"];
        };
      };
    };
  };
  listEstimates: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EstimateListResponseDto"];
        };
      };
    };
  };
  getEstimateVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EstimateVersionDto"];
        };
      };
    };
  };
  createEstimateVersionForLead: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateEstimateVersionDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EstimateVersionDto"];
        };
      };
    };
  };
  reviseEstimate: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateEstimateVersionDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EstimateVersionDto"];
        };
      };
    };
  };
  submitEstimateVersion: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EstimateVersionDto"];
        };
      };
    };
  };
  approveEstimateVersion: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EstimateVersionDto"];
        };
      };
    };
  };
  createQuoteFromEstimateVersion: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuoteVersionDto"];
        };
      };
    };
  };
  listQuotes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuoteListResponseDto"];
        };
      };
    };
  };
  getQuote: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuoteVersionDto"];
        };
      };
    };
  };
  reviseQuote: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuoteVersionDto"];
        };
      };
    };
  };
  approveQuoteVersion: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuoteVersionDto"];
        };
      };
    };
  };
  sendQuoteVersion: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendQuoteDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SendQuoteResponseDto"];
        };
      };
    };
  };
  withdrawQuoteVersion: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuoteVersionDto"];
        };
      };
    };
  };
  expireQuoteVersion: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuoteVersionDto"];
        };
      };
    };
  };
  getPublicQuote: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicQuoteDto"];
        };
      };
    };
  };
  acceptPublicQuote: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcceptQuoteDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AcceptQuoteResponseDto"];
        };
      };
    };
  };
  declinePublicQuote: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeclineQuoteDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicQuoteDto"];
        };
      };
    };
  };
}
