/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getLiveHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getReadyHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getCurrentSession"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    LiveHealthDto: {
      /** @example ok */
      status: string;
      /** Format: date-time */
      timestamp: string;
    };
    ReadinessChecksDto: {
      /** @enum {string} */
      database: "ready";
      /** @enum {string} */
      migrations: "ready";
      /** @enum {string} */
      objectStorage: "ready";
      /** @enum {string} */
      worker: "ready" | "skipped";
    };
    ReadyHealthDto: {
      checks: components["schemas"]["ReadinessChecksDto"];
      /** @example ready */
      status: string;
      /** Format: date-time */
      timestamp: string;
    };
    ApiErrorDetailDto: {
      code: string;
      correlationId: string;
      details?: Record<string, never>;
      message: string;
    };
    ApiErrorResponseDto: {
      error: components["schemas"]["ApiErrorDetailDto"];
    };
    SessionDto: {
      permissions: string[];
      /** Format: uuid */
      tenantId: string;
      /** Format: uuid */
      userId: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getLiveHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LiveHealthDto"];
        };
      };
    };
  };
  getReadyHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyHealthDto"];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponseDto"];
        };
      };
    };
  };
  getCurrentSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionDto"];
        };
      };
    };
  };
}
